# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170116_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_Token',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
